name: Tests

on:
  push: ~
  pull_request: ~

jobs:
  pytest:
    name: Python on ${{ matrix.python }} and Sphinx ${{ matrix.sphinx }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [ 3.8, 3.9, 3.10, 3.11, 3.12 ]
        sphinx: [ 4.*, 5.*, 6.*, 7.* ]
    steps:
      - name: Update code
        uses: actions/checkout@v2
      - name: Install dependencies (Sphinx ${{ matrix.sphinx }})
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          SPHINX_VERSION: ${{ matrix.sphinx }}
        run: |
          ./run init
          ./run deps
      - name: Run tests
        env:
          PYTHON_VERSION: ${{ matrix.python }}
        run: ./run tests
